"""
Download the '140k Real and Fake Faces' dataset for deepfake detection training.

Dataset: https://www.kaggle.com/datasets/xhlulu/140k-real-and-fake-faces
- 70,000 real face images from Flickr-Faces-HQ (FFHQ)
- 70,000 fake face images generated by StyleGAN
- All images are 256x256 pre-cropped faces

Usage:
  python download_kaggle.py [--max-per-class N]
"""

import os
import sys
import zipfile
import shutil
import random
import glob
import argparse
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
KAGGLE_DATASET_SLUG = "xhlulu/140k-real-and-fake-faces"
DOWNLOAD_DIR = "raw_data"
DEST_DIR = "dataset"
DEFAULT_MAX_PER_CLASS = 5000


def parse_args():
    parser = argparse.ArgumentParser(description="Download deepfake training dataset")
    parser.add_argument(
        "--max-per-class",
        type=int,
        default=DEFAULT_MAX_PER_CLASS,
        help=f"Maximum images per class (default: {DEFAULT_MAX_PER_CLASS}). "
             f"Set to 0 for unlimited.",
    )
    parser.add_argument(
        "--val-split",
        type=float,
        default=0.2,
        help="Fraction of data to use for validation (default: 0.2)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducible splits (default: 42)",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Kaggle Download
# ---------------------------------------------------------------------------
def download_and_extract():
    """Download dataset via Kaggle API."""
    try:
        import kaggle
        kaggle.api.authenticate()
        print("[OK] Authenticated with Kaggle API.")
    except Exception as e:
        print(f"[FAIL] Kaggle authentication failed: {e}")
        print("  Make sure your Kaggle token is saved at ~/.kaggle/access_token")
        print("  Or set the KAGGLE_API_TOKEN environment variable.")
        sys.exit(1)

    os.makedirs(DOWNLOAD_DIR, exist_ok=True)
    print(f"Downloading {KAGGLE_DATASET_SLUG} via Kaggle API...")
    print("  (This is ~1.2 GB, may take a few minutes...)")

    try:
        import kaggle
        kaggle.api.dataset_download_files(
            KAGGLE_DATASET_SLUG, path=DOWNLOAD_DIR, unzip=False
        )
    except Exception as e:
        print(f"[FAIL] Kaggle download failed: {e}")
        sys.exit(1)

    # Extract
    zips = glob.glob(os.path.join(DOWNLOAD_DIR, "*.zip"))
    if not zips:
        print("[FAIL] No zip file found after download.")
        sys.exit(1)

    for zf in zips:
        print(f"Extracting {zf}...")
        with zipfile.ZipFile(zf, "r") as z:
            z.extractall(DOWNLOAD_DIR)

    print("[OK] Download and extraction complete.")


# ---------------------------------------------------------------------------
# Dataset Organization
# ---------------------------------------------------------------------------
def find_images(base_dir):
    """Recursively find all images and classify them as real or fake based on path."""
    real_images = []
    fake_images = []
    extensions = {".png", ".jpg", ".jpeg", ".bmp", ".webp"}

    for root, _, files in os.walk(base_dir):
        for file in files:
            if Path(file).suffix.lower() in extensions:
                full_path = os.path.join(root, file)
                parts = [p.lower() for p in Path(full_path).parts]

                if "real" in parts:
                    real_images.append(full_path)
                elif "fake" in parts:
                    fake_images.append(full_path)

    return real_images, fake_images


def sort_into_train_val(max_per_class, val_split, seed):
    """Sort downloaded images into train/val structure."""
    print("\nOrganizing images into train/val structure...")

    real_images, fake_images = find_images(DOWNLOAD_DIR)
    print(f"  Found {len(real_images)} real images")
    print(f"  Found {len(fake_images)} fake images")

    if len(real_images) == 0 or len(fake_images) == 0:
        print("\n[FAIL] ERROR: Could not find real/fake images in the downloaded data.")
        print("  Directory contents:")
        for root, dirs, files in os.walk(DOWNLOAD_DIR):
            depth = root.replace(DOWNLOAD_DIR, "").count(os.sep)
            if depth <= 3:
                indent = "    " * depth
                print(f"  {indent}{os.path.basename(root)}/ ({len(files)} files)")
        sys.exit(1)

    random.seed(seed)
    random.shuffle(real_images)
    random.shuffle(fake_images)

    if max_per_class > 0:
        real_images = real_images[:max_per_class]
        fake_images = fake_images[:max_per_class]
        print(f"  Limiting to {max_per_class} images per class")

    min_count = min(len(real_images), len(fake_images))
    real_images = real_images[:min_count]
    fake_images = fake_images[:min_count]
    print(f"  Balanced to {min_count} images per class")

    if os.path.exists(DEST_DIR):
        print(f"  Removing old dataset at {DEST_DIR}/...")
        shutil.rmtree(DEST_DIR)

    def split_and_copy(images, label):
        split_idx = int(len(images) * (1 - val_split))
        train_imgs = images[:split_idx]
        val_imgs = images[split_idx:]

        train_dir = os.path.join(DEST_DIR, "train", label)
        val_dir = os.path.join(DEST_DIR, "val", label)
        os.makedirs(train_dir, exist_ok=True)
        os.makedirs(val_dir, exist_ok=True)

        for i, img_path in enumerate(train_imgs):
            ext = Path(img_path).suffix
            dest = os.path.join(train_dir, f"{label}_{i:06d}{ext}")
            shutil.copy2(img_path, dest)

        for i, img_path in enumerate(val_imgs):
            ext = Path(img_path).suffix
            dest = os.path.join(val_dir, f"{label}_{i:06d}{ext}")
            shutil.copy2(img_path, dest)

        print(f"  [OK] {label}: {len(train_imgs)} train, {len(val_imgs)} val")

    split_and_copy(real_images, "real")
    split_and_copy(fake_images, "fake")

    print(f"\n[OK] Dataset ready at ./{DEST_DIR}/")
    print(f"  Structure:")
    print(f"    {DEST_DIR}/train/real/  - training real faces")
    print(f"    {DEST_DIR}/train/fake/  - training fake faces")
    print(f"    {DEST_DIR}/val/real/    - validation real faces")
    print(f"    {DEST_DIR}/val/fake/    - validation fake faces")


def cleanup_raw_data():
    """Remove raw download data to save disk space."""
    if os.path.exists(DOWNLOAD_DIR):
        print(f"\nCleaning up {DOWNLOAD_DIR}/...")
        shutil.rmtree(DOWNLOAD_DIR)
        print("[OK] Cleanup complete.")


def main():
    args = parse_args()

    print("=" * 60)
    print("  Deepfake Dataset Downloader")
    print("  Dataset: 140k Real and Fake Faces (FFHQ + StyleGAN)")
    print(f"  Max per class: {args.max_per_class or 'unlimited'}")
    print(f"  Val split: {args.val_split:.0%}")
    print("=" * 60)

    download_and_extract()
    sort_into_train_val(args.max_per_class, args.val_split, args.seed)
    cleanup_raw_data()

    print("\n" + "=" * 60)
    print("  [OK] All done! Next steps:")
    print("    1. python train.py          - Train the model")
    print("    2. python evaluate_model.py - Evaluate model performance")
    print("    3. python app.py            - Start the inference server")
    print("=" * 60)


if __name__ == "__main__":
    main()
