import { AgentResult } from '../types';

export const buildReportText = (analysis: AgentResult): string => {
  return `
SACHAI – FORENSIC & OSINT REPORT
================================

FINAL VERDICT
-------------
${analysis.verdict}

INTEGRITY SCORE
---------------
${analysis.integrityScore}%

RISK LEVEL
----------
${analysis.riskLevel}

TECHNICAL SUMMARY
-----------------
${analysis.explanation}

DETECTED ANOMALIES
------------------
${analysis.anomalies?.map(
  (a, i) => `${i + 1}. ${a.description} (Severity: ${a.severity}, Time: ${a.timestamp}s)`
).join('\n') || 'None detected'}

OSINT & CIRCULATION INTELLIGENCE
--------------------------------
Probable Origin   : ${analysis.probableOrigin || 'Unknown'}
Content Theme    : ${analysis.contentTheme || 'Unclassified'}
OSINT Confidence : ${analysis.osintConfidence || 'Low'}

Likely Circulation Channels:
${analysis.circulationChannels?.join(', ') || 'Undetermined'}

SAFETY RECOMMENDATION
---------------------
${analysis.safetyRecommendation}

Generated by SachAI – Neural Forensics Unit
Timestamp: ${new Date().toISOString()}
`;
};

export const copyReportToClipboard = async (analysis: AgentResult): Promise<void> => {
  const text = buildReportText(analysis);
  await navigator.clipboard.writeText(text);
};

export const copyTextToClipboard = async (text: string): Promise<void> => {
  await navigator.clipboard.writeText(text);
};
